---
title: 'Homework 1: Exploratory Data Analysis'
author: "IE 2064 Data Science"
output:
  pdf_document: default
  html_document: default
---

1. Load the `ChemicalManufacturingProcess` dataset 
from Applied Predictive Models (APM) Chapter 1.4.
2. Describe all of the fields in the data set. Note: you may group fields if it 
makes sense.  If there are a very large number of fields, pick ten.
    i. Name
    ii. Provide a short, one sentence description. Note: do you best on this 
    given the available information. Many (or all) the variables may have the
    same description.
    iii. Description of potential values (include data type and units if possible)
    iv. Summary statistics: mean, median, quartiles, range if applicable
    v. Is this an outcome or a potential predictor? 
    (dependent or independent variable)
3.  Write a CoNVO statement for the dataset (200-400 words).
4.  Create a pairs plot. Identify which predictor variables seem to produce 
variation in the outcome variables.  If there are more than 5 variables in the
data set you should select (with justification) 5 variables to include in the 
pairs plot.
5.  Identify an outcome and three predictor variables based on your CoNVO 
statement and the pairs plot.
6.  Explore the variables by applying at least four different plot types. 
For each plot write a one sentence description of the relationship you see.
7. Suggest possible reasons for relationships between variables.
Use causal diagrams in your discussion.

Submit a rmd file and knitted pdf document. I should be able to knit the file
after downloading the appropriate dataset.

**Reminder:** all plots should be clearly labeled.

## Downloading data sets 

* The permeability, chemical manufacturing, and hepatic injury datasets are 
available by:

```{r}
library(AppliedPredictiveModeling)
data()
```

* The grant data and German credit data sources are found by following the 
instructions in http://appliedpredictivemodeling.com/data.
 
* The music genre data set appears to be no longer available. 