---
title: 'Homework 1: Exploratory Data Analysis'
author: "Alex Czerkawski"
output:
  pdf_document: default
  html_document: default
editor_options: 
  markdown: 
    wrap: 72
---

## Dataset choice

For this assignment, we will be using the Chemical Manufacturing Process
dataset. This dataset was taken from Applied Predictive Models (APM)
Chapter 1.4.

```{r,echo=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(caret)
library(AppliedPredictiveModeling)
data(ChemicalManufacturingProcess)
df <- ChemicalManufacturingProcess
```

## Identify an outcome variable to be predicted

-   **Yield** (continuous) = Final product yield. A summary of this
    column is:

```{r,echo=FALSE}
summary(df$Yield)
```

## Preprocessing

```{r,echo=FALSE}
df <- df %>% filter(!if_any(everything(), is.na))
dfX <- df %>% select(-Yield)
```

## Model Fitting

```{r, echo=FALSE}
ctrl <- trainControl(method = "cv", number = 10)
# Linear regression
lmTune <- train(Yield ~., df,
                  method='lm',
                  trControl=ctrl,
                  preProc = c('center', 'scale'))
lmTune
```

```{r, echo=FALSE}
# Lasso
set.seed(100)
lassoGrid <- expand.grid(lambda = c(0), 
                      fraction = seq(.01, 1, length = 20))
lassoTune <- train(x = (dfX), y = df$Yield,
                    method = "enet",
                    tuneGrid = lassoGrid,
                    trControl = ctrl,
                    preProc = c("center", "scale")
                  )

lassoTune
```

```{r, echo=FALSE}
# Ridge regression
set.seed(100)
ridgeGrid <- expand.grid(lambda = seq(0, .1, length = 20))
ridgeTune <- train(x = dfX, y = df$Yield,
                   method = "ridge",
                   tuneGrid = ridgeGrid,
                   trControl = ctrl,
                   preProc = c("center", "scale")
              )
ridgeTune
```

```{r, echo=FALSE}
# Support Vector Machines (SVM)

```

```{r, echo=FALSE}
# Neural Nets

```

```{r, echo=FALSE}
# Multivariate Adaptive Regression Splines (MARS)

```

```{r, echo=FALSE}
# K-nearest Neighbors (KNN)

```

```{r, echo=FALSE}
# Regression tree

```

```{r, echo=FALSE}
# Random forests

```

## Model comparison



## Recommendation

