---
title: 'Homework 3: Classification'
author: "IE 2064 Data Science"
output:
  pdf_document: default
  html_document: default
---

1.  Load the `Hepatic Injury` dataset from Applied Predictive Models (APM) Chapter 1.4.
2.  Simplify the `injury` data into `injury` and `no injury`
3.  Identify a variable that you will attempt to predict using classification
    i. Name
    ii. Short, one sentence description
    iii. Description of potential values (include data type and units)
    iv. Histogram plot
4.  Appropriately preprocess the data
5.  Use 10 fold cross validation to fit a model from each of the following 
categories:
    i. Linear models  
        1. Logistic regression
        2. Linear discriminant analysis
        3. Penalized models
    ii. Trees
        1. Classification trees
        2. Random forests
    iii. Non-linear models
        1. Support Vector Machines (SVM)
        2. Neural Nets
        3. Non-linear discriminant analysis
        4. K-nearest Neighbors (KNN)
        5. Naive Bayes
6. Compare each of the models you fitted in terms of their accuracy and
ROC curves
7. Which model would you recommend using and why?